### ISSUE TITLE
Page refreshing 

### ISSUE THREAD

**Issue by pcrjntuk** [stackadroit/easyslotbooking-ext#1]
Hello,

Today i started subscription for  easyslotbooking, i am checking slots for multiple locations like Delhi and Mumbai but while switching location dropdown the entire page is getting refreshed, due to this my login attempts are exhausting. Actually in new website https://www.usvisascheduling.com/ no need to refresh the entire page while switching location dropdown , it was there in previous CGI Portal and it was website behavior but in new website tool only refreshing entire page and selecting new location.

**Comment by polupraneeth** [comment]
It looks like the page refresh issue with the EasySlotBooking extension might be due to the "Check Dates in Loop" feature in the settings. This option causes the page to refresh if no dates are found in all selected consulates, to restart the search. To stop the page from refreshing, you can try disabling this feature in the extension's settings. If the problem continues, further investigation might be needed.

https://youtu.be/2qsCFmw3rL8?si=CvsCPGLyWZr4Dmts&t=350

**Comment by pcrjntuk** [comment]
I noticed that, than what is the use of tool if exhausting logins?. even if i don't select "Check Dates in Loop" feature, it will navigate to home page and then if you run tool again it will go to OFC page means it's refreshing.  so we're expecting tool to check visa slots from OFC page instead of starts from Home page and keep check either certain point of time or until stop tool and then stay in OFC page if no slots found. this way we can logout after sometime if we don't find slots. you know well slots won't stay more than 10 to 20 seconds.

so better stay in OFC page itself instead of going to home page and come back to OFC page.

**Comment by polupraneeth** [comment]
Added the requested functionality to the EasySlotBooking extension version 4.0.6
